### PR TITLE
Replace old selectors

### PR DESCRIPTION
**Pull request by intrnl**
Replacing based on this [gist](https://gist.github.com/intrnl/b758b9d9ed5c05e6377b27d647b11d91)

### CODE REVIEW

**Comment by BakaTekku** [comment]
Sorry for not seeing this earlier I would accept the pull request but Discord changed the element names again. which made this outdated thanks for the effort.

**Comment by intrnl** [comment]
You sure? This was made days after Discord rerolled all the obfuscated classnames.

**Comment by BakaTekku** [comment]
Yeah I compared your changes to the current CSS they rolled back but later changed the names after they pushed an update like a day or 2 after you sent this in. although if i made a mistake let me know.

diff

**Comment by intrnl** [comment]
Hmm, yeah, I think I might've missed some of the stuff due to a bug with my replacer script. Thanks for telling me though!

**Pull request closed without merging**
