### PR TITLE
Fixed "META Not Found" issue

### PR DESCRIPTION
**Pull request by pilppe**
Just a quick fix on one of my favorite themes :)

Not sure what version this is on but I added it.

### CODE REVIEW

**Comment by BakaTekku** [comment]
This is for BeautifulDiscord it wont hurt to add this i suppose.

**Comment by pilppe** [comment]
BeautifulDiscord doesn't work for me at all so I tried BandagedBD and it worked very well. I would rather go for an updated version than to use an older one

**Comment by pilppe** [comment]
I made the "Join" button light up when previously when you hovered over it with your mouse it was completely black compared to the left side which was light up. Personally it looks better. And I changed the border-color of new messages bar and jump-to-present bar to a nice lighter red. 👍 

Also, renamed theme.css to DarkDiscord.theme.css so it supports BetterDiscord.

previously

**Comment by BakaTekku** [comment]
Much appreciated I went ahead and fixed a few things.
as for betterdiscord  not sure if i should merge as this is outdated now

**Comment by pilppe** [comment]
I can't say it's outdated, it works without problems with BetterDiscord

**Pull request closed without merging**
